// Seznam 38 konstruktérů z custom view "RAIL+EL"
// Tento seznam se používá pro zákaznický pohled, který je veřejný (bez přihlášení)
export const RAIL_EL_ENGINEERS = [
  'Ambrož David',
  'Anovčín Branislav',
  'Bartovič Anton',
  'Bohušík Martin',
  'Brojír Jaroslav',
  'Břicháček Miloš',
  'Fenyk Pavel',
  'Fica Ladislav',
  'Friedlová Jiřina',
  'Fuchs Pavel',
  'Heřman Daniel',
  'Hibler František',
  'Hlavan Martin',
  'Chrenko Daniel',
  'Chrenko Peter',
  'Jandečka Karel',
  'Ješš Jozef',
  'Jurčišin Peter',
  'Kalafa Ján',
  'Karlesz Michal',
  'Karlík Štěpán',
  'Klíma Milan',
  'Lengyel Martin',
  'Madanský Peter',
  'Matta Jozef',
  'Melichar Ondřej',
  'Mohelník Martin',
  'Nedavaška Petr',
  'Pecinovský Pavel',
  'Púpava Marián',
  'Pytela Martin',
  'Samko Mikuláš',
  'Slavík Ondřej',
  'Šedovičová Darina',
  'Šoupa Karel',
  'Uher Tomáš',
  'Večeř Jiří',
  'Weiss Ondřej'
];
